### PR TITLE
Allow customizing soft break mode

### LINKED ISSUE #341: New lines are concatenated and not broken, need two lines
**Describe the bug**
When I have a Markdown as follows:

```swift
Markdown(
    """
    Test1
    Test2
    Test3
    """
)
```

I get the following result: 

image

If I add an extra line between them, they get separated:

To me, this seems like the wrong behavior, as you can see even from the markdown rendered here in GitHub:

Test1
Test2
Test3

Is there any way to fix it, or control this behavior? 

Thanks :) 

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
Shown in problem description

**Expected behavior**
Shown in problem description

**Screenshots**
Shown in problem description

**Version information**
- MarkdownUI: [e.g. 2.0.0, or a commit hash]
- OS: iOS 17.4
- Xcode: 16 Beta 5

**Additional context**

### PR DESCRIPTION
**Pull request by freak4pc**
Hey @gonzalezreal :) 
I wanted to put up a quick PR to make sure this direction is acceptable to you.

If yes, I'll add some tests and prepare it for merging. 

Thank you! 

Resolved #341

### CODE REVIEW

**Comment by gonzalezreal** [comment]
Hey @freak4pc,

This pull request goes in the right direction 💪🏽.

You will probably need to update `AttributedStringInlineRenderer` as well. `TextInlineRenderer` only works with the first level of inlines. It is a hack to enable inline images by leveraging `Text.init(_ image: Image)`. Nested inlines are rendered by the `AttributedStringInlineRenderer`.

Let me know if you need any further clarification.

Thanks!

**Comment by freak4pc** [comment]
Should be good to go, let me know what you think @gonzalezreal 
One point is that I'm running Xcode 16 for the tests so they're all failing, I don't have access to Xcode 14.2 like the CI runs (also problematic since it won't even run on macOS Mojave for me :P). Perhaps you could run it locally somehow?

**Comment by gonzalezreal** [comment]
Xcode version shouldn't be an issue as long as you can create an iOS 16.2 iPhone SE (3rd generation) simulator, which is the one used to generate the snapshot images. You can use these ones:

| testSoftBreakModeLineBreak.1  | testSoftBreakModeSpace.1 |
| ------------- | ------------- |
|   |   |

**Comment by freak4pc** [comment]
@gonzalezreal  Pushed your files. Thanks :)

**Comment by gonzalezreal** [comment]
Awesome contribution. Thanks, @freak4pc!

**Comment by freak4pc** [comment]
Thank you for the prompt review! 🙏

**Comment by freak4pc** [comment]
One final ask, any chance for a release cut when you have a moment? ^_^

**Pull request merged**
